const CATEGORY_CARD_IMAGES: Record<string, string> = {
  "adventure-for-singles": "/images/site/home/browse-category-tiles/home-cat-activities.webp",
  "beauty-for-singles": "/images/categories/cards/beauty-for-singles.webp",
  "comedians": "/images/categories/cards/comedians.webp",
  "cruises4singles": "/images/categories/cards/cruises4singles.webp",
  "dance-ballroom-style": "/images/categories/cards/dance-ballroom-style.webp",
  "dance-bachata": "/images/categories/cards/dance-bachata.webp",
  "dance-ceroc": "/images/categories/cards/dance-ceroc.webp",
  "dance-classes": "/images/categories/cards/dance-classes.webp",
  "dance-fitness-and-health": "/images/categories/cards/dance-fitness-and-health.webp",
  "dance-latin-style": "/images/categories/cards/dance-latin-style.webp",
  "dance-line-dancing": "/images/categories/cards/dance-line-dancing.webp",
  "dance-modern-style": "/images/categories/cards/dance-modern-style.webp",
  "dance-party-clubs": "/images/categories/cards/dance-party-clubs.webp",
  "dance-salsa": "/images/categories/cards/dance-salsa.webp",
  "dance-styles": "/images/categories/cards/dance-styles.webp",
  "dance-swing": "/images/categories/cards/dance-swing.webp",
  "dance-tango": "/images/categories/cards/dance-tango.webp",
  "dance-teachers": "/images/categories/cards/dance-teachers.webp",
  "dating-coaches": "/images/categories/cards/dating-coaches.webp",
  "dating-profile-photography": "/images/categories/cards/dating-profile-photography.webp",
  "dinner-for-six": "/images/site/home/experience-cards/home-exp-dinner-parties.jpg",
  "dinner-parties": "/images/site/home/browse-category-tiles/home-cat-dinner-parties.webp",
  "finance-mortgage": "/images/categories/cards/finance-mortgage.webp",
  "fitness4singles": "/images/categories/cards/fitness4singles.webp",
  "function-centres": "/images/categories/cards/function-centres.webp",
  "golf": "/images/categories/cards/golf.webp",
  "healing-and-happiness": "/images/categories/cards/healing-and-happiness.webp",
  "houseparties": "/images/categories/cards/houseparties.webp",
  "image-and-photography": "/images/categories/cards/image-and-photography.webp",
  "intro-agencies": "/images/categories/cards/intro-agencies.webp",
  "jazz": "/images/categories/cards/jazz.webp",
  "lgbtqia-singles-events": "/images/categories/cards/lgbtqia-singles-events.webp",
  "life-coaches": "/images/categories/cards/life-coaches.webp",
  "lotto4singles": "/images/categories/cards/lotto4singles.webp",
  "mature-dating-events": "/images/categories/cards/mature-dating-events.webp",
  "nightclubs": "/images/categories/cards/nightclubs.webp",
  "online-dating": "/images/categories/cards/online-dating.webp",
  "online-dating-international": "/images/categories/cards/online-dating-international.webp",
  "psychics4singles": "/images/categories/cards/psychics4singles.webp",
  "psychology": "/images/categories/cards/psychology.webp",
  "restaurants-cafes": "/images/categories/cards/restaurants-cafes.webp",
  "retreats-for-singles": "/images/categories/cards/retreats-for-singles.webp",
  "seminars": "/images/categories/cards/seminars.webp",
  "singles-health": "/images/categories/cards/singles-health.webp",
  "singles-mixers": "/images/categories/cards/singles-mixers.webp",
  "christian-singles": "/images/categories/cards/christian-singles.webp",
  "singles-products": "/images/categories/cards/singles-products.webp",
  "sms-phone-dating": "/images/categories/cards/sms-phone-dating.webp",
  "social-clubs": "/images/categories/cards/social-clubs.webp",
  "social-walks": "/images/categories/cards/social-walks.webp",
  "solo-travel": "/images/categories/cards/solo-travel.webp",
  "speed-dating": "/images/site/home/browse-category-tiles/home-cat-speed-dating.webp",
  "sport-adventure": "/images/site/home/browse-category-tiles/home-cat-activities.webp",
  "tours4singles": "/images/categories/cards/tours4singles.webp",
  "travel-for-singles": "/images/categories/cards/travel-for-singles.webp",
  "walks4singles": "/images/categories/cards/walks4singles.webp",
  "wineries4singles": "/images/categories/cards/wineries4singles.webp",
  "yoga-classes": "/images/categories/cards/yoga-classes.webp",
};

const CATEGORY_CARD_SUMMARIES: Record<string, string> = {
  "adventure-for-singles": "Outdoor activities and shared experiences with a little momentum.",
  "beauty-for-singles": "Grooming, presentation and confidence services for singles.",
  "comedians": "Comedy nights and lighter social entertainment.",
  "cruises4singles": "Social outings on the water with room to mingle.",
  "dance-ballroom-style": "Classic partner dancing with structure, rhythm and easy social connection.",
  "dance-bachata": "Modern Latin partner dancing with an easy, social rhythm.",
  "dance-ceroc": "Modern partner dancing with an easy social rhythm.",
  "dance-classes": "Learn, move and meet people in a relaxed class setting.",
  "dance-fitness-and-health": "Movement-based classes for energy, confidence and wellbeing.",
  "dance-latin-style": "Latin dance classes and socials with warmth, rhythm and connection.",
  "dance-line-dancing": "No-partner group dancing with repeatable steps and easy confidence.",
  "dance-modern-style": "Contemporary movement classes with expressive, social energy.",
  "dance-party-clubs": "Music, movement and social nights with energy.",
  "dance-salsa": "Latin dance classes and salsa social nights.",
  "dance-styles": "Different dance styles for singles who want to explore what fits.",
  "dance-swing": "Playful swing and jive classes with upbeat social energy.",
  "dance-tango": "Elegant tango classes, socials and dance communities.",
  "dance-teachers": "Dance instructors and class providers for singles.",
  "dating-coaches": "Dating-specific support for confidence, profiles and relationship readiness.",
  "dating-profile-photography": "Profile-focused portraits that help singles show up naturally.",
  "dinner-for-six": "Smaller hosted meals with easier conversation.",
  "dinner-parties": "Longer conversations over a shared meal.",
  "finance-mortgage": "Money, mortgage and practical support for life planning.",
  "fitness4singles": "Movement, health and energy with social possibility.",
  "function-centres": "Venues and event spaces suited to singles gatherings.",
  "golf": "Golf days, clubs and social rounds for singles.",
  "healing-and-happiness": "Wellbeing services for renewal and balance.",
  "houseparties": "Hosted home-style gatherings and relaxed social nights.",
  "image-and-photography": "Presentation, confidence and profile-ready imagery.",
  "intro-agencies": "Personalised matching and more guided support.",
  "jazz": "Live music nights and jazz venues with social atmosphere.",
  "lgbtqia-singles-events": "Inclusive singles events and social spaces for LGBTQIA+ communities.",
  "life-coaches": "Guidance for goals, confidence and personal direction.",
  "lotto4singles": "Lighthearted prize, lotto and chance-based offers for singles.",
  "mature-dating-events": "Dating experiences for singles later in life.",
  "nightclubs": "Late-night venues and social dance floors.",
  "online-dating": "Digital dating options to support your wider search.",
  "online-dating-international": "International online dating services for singles looking further afield.",
  "psychics4singles": "Intuitive, spiritual and psychic services for singles.",
  "psychology": "Professional support for emotional wellbeing and patterns.",
  "restaurants-cafes": "Dining venues, cafes and social food experiences.",
  "retreats-for-singles": "Retreats, reset weekends and reflective escapes for singles.",
  "seminars": "Learning experiences for personal and social growth.",
  "singles-health": "Health-focused support for a stronger everyday life.",
  "singles-mixers": "Relaxed hosted socials where meeting new people is the point.",
  "christian-singles": "Faith-aligned events, groups and services for Christian singles.",
  "singles-products": "Products, gifts and resources aimed at singles.",
  "sms-phone-dating": "Phone and text-based dating options for low-pressure connection.",
  "social-clubs": "Regular groups and hosted gatherings for singles.",
  "social-walks": "Low-pressure walks and outdoor catch-ups with easy conversation.",
  "solo-travel": "Travel experiences built for independent singles and solo guests.",
  "speed-dating": "Short, hosted introductions with a clear dating purpose.",
  "sport-adventure": "Active events for people who like to do, not just sit.",
  "tours4singles": "Shared trips and discovery with other singles.",
  "travel-for-singles": "Trips and getaways with other singles.",
  "walks4singles": "Easy conversation while exploring local places.",
  "wineries4singles": "Cellar doors, tastings and relaxed vineyard social outings.",
  "yoga-classes": "Calm, strength and self-connection through practice.",
};

const CATEGORY_HERO_IMAGES: Record<string, string> = {
  "adventure-for-singles": "/images/categories/heroes/adventure-for-singles.webp",
  "beauty-for-singles": "/images/categories/heroes/beauty-for-singles.webp",
  "comedians": "/images/categories/heroes/comedians.webp",
  "cruises4singles": "/images/categories/heroes/cruises4singles.webp",
  "dance-ballroom-style": "/images/categories/heroes/dance-ballroom-style.webp",
  "dance-bachata": "/images/categories/heroes/dance-bachata.webp",
  "dance-ceroc": "/images/categories/heroes/dance-ceroc.webp",
  "dance-classes": "/images/categories/heroes/dance-classes.webp",
  "dance-fitness-and-health": "/images/categories/heroes/dance-fitness-and-health.webp",
  "dance-latin-style": "/images/categories/heroes/dance-latin-style.webp",
  "dance-line-dancing": "/images/categories/heroes/dance-line-dancing.webp",
  "dance-modern-style": "/images/categories/heroes/dance-modern-style.webp",
  "dance-party-clubs": "/images/categories/heroes/dance-party-clubs.webp",
  "dance-salsa": "/images/categories/heroes/dance-salsa.webp",
  "dance-styles": "/images/categories/heroes/dance-styles.webp",
  "dance-swing": "/images/categories/heroes/dance-swing.webp",
  "dance-tango": "/images/categories/heroes/dance-tango.webp",
  "dance-teachers": "/images/categories/heroes/dance-teachers.webp",
  "dating-coaches": "/images/categories/heroes/dating-coaches.webp",
  "dating-profile-photography": "/images/categories/heroes/dating-profile-photography.webp",
  "dinner-for-six": "/images/categories/heroes/dinner-for-six.webp",
  "dinner-parties": "/images/categories/heroes/dinner-parties.webp",
  "finance-mortgage": "/images/categories/heroes/finance-mortgage.webp",
  "fitness4singles": "/images/categories/heroes/fitness4singles.webp",
  "function-centres": "/images/categories/heroes/function-centres.webp",
  "golf": "/images/categories/heroes/golf.webp",
  "healing-and-happiness": "/images/categories/heroes/healing-and-happiness.webp",
  "houseparties": "/images/categories/heroes/houseparties.webp",
  "image-and-photography": "/images/categories/heroes/image-and-photography.webp",
  "intro-agencies": "/images/categories/heroes/intro-agencies.webp",
  "jazz": "/images/categories/heroes/jazz.webp",
  "lgbtqia-singles-events": "/images/categories/heroes/lgbtqia-singles-events.webp",
  "life-coaches": "/images/categories/heroes/life-coaches.webp",
  "lotto4singles": "/images/categories/heroes/lotto4singles.webp",
  "mature-dating-events": "/images/categories/heroes/mature-dating-events.webp",
  "nightclubs": "/images/categories/heroes/nightclubs.webp",
  "online-dating": "/images/categories/heroes/online-dating.webp",
  "online-dating-international": "/images/categories/heroes/online-dating-international.webp",
  "psychics4singles": "/images/categories/heroes/psychics4singles.webp",
  "psychology": "/images/categories/heroes/psychology.webp",
  "restaurants-cafes": "/images/categories/heroes/restaurants-cafes.webp",
  "retreats-for-singles": "/images/categories/heroes/retreats-for-singles.webp",
  "seminars": "/images/categories/heroes/seminars.webp",
  "singles-health": "/images/categories/heroes/singles-health.webp",
  "singles-mixers": "/images/categories/heroes/singles-mixers.webp",
  "christian-singles": "/images/categories/heroes/christian-singles.webp",
  "singles-products": "/images/categories/heroes/singles-products.webp",
  "sms-phone-dating": "/images/categories/heroes/sms-phone-dating.webp",
  "social-clubs": "/images/categories/heroes/social-clubs.webp",
  "social-walks": "/images/categories/heroes/social-walks.webp",
  "solo-travel": "/images/categories/heroes/solo-travel.webp",
  "speed-dating": "/images/categories/heroes/speed-dating.webp",
  "sport-adventure": "/images/categories/heroes/sport-adventure.webp",
  "tours4singles": "/images/categories/heroes/tours4singles.webp",
  "travel-for-singles": "/images/categories/heroes/travel-for-singles.webp",
  "walks4singles": "/images/categories/heroes/walks4singles.webp",
  "wineries4singles": "/images/categories/heroes/wineries4singles.webp",
  "yoga-classes": "/images/categories/heroes/yoga-classes.webp",
};

const GENERATED_CATEGORY_HERO_SLUGS = new Set([
  "adventure-for-singles",
  "beauty-for-singles",
  "comedians",
  "cruises4singles",
  "dance-ceroc",
  "dance-classes",
  "dance-party-clubs",
  "dance-salsa",
  "dance-tango",
  "dance-teachers",
  "dinner-for-six",
  "dinner-parties",
  "finance-mortgage",
  "fitness4singles",
  "function-centres",
  "golf",
  "healing-and-happiness",
  "houseparties",
  "image-and-photography",
  "intro-agencies",
  "jazz",
  "life-coaches",
  "lotto4singles",
  "mature-dating-events",
  "nightclubs",
  "online-dating",
  "online-dating-international",
  "psychics4singles",
  "psychology",
  "restaurants-cafes",
  "seminars",
  "singles-health",
  "singles-products",
  "sms-phone-dating",
  "social-clubs",
  "speed-dating",
  "sport-adventure",
  "tours4singles",
  "travel-for-singles",
  "walks4singles",
  "wineries4singles",
  "yoga-classes",
]);

function getGeneratedCategoryHeroFallback(slug: string): string | undefined {
  const normalizedSlug = slug.replace(/_/g, "-");
  if (!GENERATED_CATEGORY_HERO_SLUGS.has(normalizedSlug)) return undefined;

  const heroSlug = normalizedSlug === "online-dating-international"
    ? "online-dating-int"
    : normalizedSlug === "wineries4singles"
      ? "wineries"
      : normalizedSlug;
  return `/images/site/category-heroes/category-hero-${heroSlug}.svg`;
}

export function getCategoryCardImage(slug: string): string | undefined {
  return CATEGORY_CARD_IMAGES[slug.replace(/_/g, "-")];
}

export function getCategoryHeroImage(slug: string): string | undefined {
  const normalizedSlug = slug.replace(/_/g, "-");
  return CATEGORY_HERO_IMAGES[normalizedSlug]
    ?? CATEGORY_CARD_IMAGES[normalizedSlug]?.replace("/cards/", "/heroes/")
    ?? getGeneratedCategoryHeroFallback(normalizedSlug);
}

export function getCategoryCardSummary(slug: string, fallback?: string | null): string {
  return CATEGORY_CARD_SUMMARIES[slug.replace(/_/g, "-")] ?? fallback ?? "";
}
