import type { Category } from "./types";

type CanonicalCategory = Omit<Category, "listing_count"> & {
  sort_order: number;
  aliases?: string[];
};

export const CANONICAL_CATEGORY_REPAIRS: CanonicalCategory[] = [
  {
    slug: "speed_dating",
    label: "Speed Dating",
    parent_slug: null,
    sort_order: 10,
    description: "Hosted short-date events for singles who want structured introductions.",
    seo_intro: "Speed dating gives singles a clear, hosted way to meet several people in one night without having to guess why anyone is there.",
    seo_title: "Speed Dating Australia | Events4Singles",
    seo_description: "Find speed dating events and hosted singles introductions around Australia.",
    hero_image_url: "/images/categories/heroes/speed-dating.webp",
  },
  {
    slug: "singles_mixers",
    label: "Singles Mixers",
    parent_slug: null,
    sort_order: 18,
    description: "Relaxed hosted socials where singles can meet new people without a heavily structured dating format.",
    seo_intro: "Singles mixers are a simple way to meet new people in a hosted social setting where conversation is expected and the pressure stays low.",
    seo_title: "Singles Mixers Australia | Events4Singles",
    seo_description: "Find singles mixers and relaxed social events for Australian singles.",
    hero_image_url: "/images/categories/heroes/singles-mixers.webp",
  },
  {
    slug: "dinner_parties",
    label: "Dinner Parties",
    parent_slug: null,
    sort_order: 20,
    description: "Hosted dinner parties, Dinner for Six style tables and shared dining events where singles can meet over a meal.",
    seo_intro: "Singles dinner parties create a warmer pace for meeting people, from intimate Dinner for Six style tables through to hosted shared meals with more time for real conversation.",
    seo_title: "Singles Dinner Parties and Dinner for Six Australia | Events4Singles",
    seo_description: "Find singles dinner parties, hosted dinners, Dinner for Six style tables and social dining events in Australia.",
    hero_image_url: "/images/categories/heroes/dinner-for-six.webp",
    aliases: ["dinner_for_six"],
  },
  {
    slug: "intro_agencies",
    label: "Introduction Agencies",
    parent_slug: null,
    sort_order: 21,
    description: "Personalised matching, dating introductions and more guided support for singles.",
    seo_intro: "Introduction agencies suit singles who want a more personal, supported approach to meeting compatible people.",
    seo_title: "Introduction Agencies Australia | Events4Singles",
    seo_description: "Find dating introduction agencies and personalised matching services for Australian singles.",
    hero_image_url: "/images/categories/heroes/intro-agencies.webp",
  },
  {
    slug: "online_dating",
    label: "Online Dating",
    parent_slug: null,
    sort_order: 22,
    description: "Digital dating services and online options for singles who want to widen their search.",
    seo_intro: "Online dating listings give singles a way to compare digital dating services, profile-based platforms and online options that can support a broader search.",
    seo_title: "Online Dating Australia | Events4Singles",
    seo_description: "Compare online dating services and digital dating options for Australian singles.",
    hero_image_url: "/images/categories/heroes/online-dating.webp",
  },
  {
    slug: "christian_singles",
    label: "Christian Singles",
    parent_slug: null,
    sort_order: 24,
    description: "Faith-aligned events, groups and services for Christian singles.",
    seo_intro: "Christian singles listings bring together social events, dating services and community-minded ways to meet people who share similar values.",
    seo_title: "Christian Singles Australia | Events4Singles",
    seo_description: "Explore Christian singles events, groups and dating services in Australia.",
    hero_image_url: "/images/categories/heroes/christian-singles.webp",
  },
  {
    slug: "lgbtqia_singles_events",
    label: "LGBTQIA+ Singles Events",
    parent_slug: null,
    sort_order: 26,
    description: "Inclusive singles events and social spaces for LGBTQIA+ communities.",
    seo_intro: "LGBTQIA+ singles events make it easier to find inclusive social nights, mixers and community spaces where singles can connect comfortably.",
    seo_title: "LGBTQIA+ Singles Events Australia | Events4Singles",
    seo_description: "Find inclusive LGBTQIA+ singles events and social spaces around Australia.",
    hero_image_url: "/images/categories/heroes/lgbtqia-singles-events.webp",
  },
  {
    slug: "mature_dating_events",
    label: "Mature Dating Events",
    parent_slug: null,
    sort_order: 28,
    description: "Dating events and social introductions for singles later in life.",
    seo_intro: "Mature dating events help singles meet in age-aware settings where conversation, comfort and intention matter.",
    seo_title: "Mature Dating Events Australia | Events4Singles",
    seo_description: "Find mature dating events and singles introductions for older adults in Australia.",
    hero_image_url: "/images/categories/heroes/mature-dating-events.webp",
  },
  {
    slug: "social_clubs",
    label: "Social Clubs",
    parent_slug: null,
    sort_order: 32,
    description: "Regular groups and hosted gatherings for singles who want a broader social life.",
    seo_intro: "Singles social clubs offer recurring outings, hosted gatherings and relaxed ways to meet new people.",
    seo_title: "Social Clubs for Singles Australia | Events4Singles",
    seo_description: "Find singles social clubs, activity groups and hosted social events around Australia.",
    hero_image_url: "/images/categories/heroes/social-clubs.webp",
  },
  {
    slug: "dance_classes",
    label: "Dance Classes",
    parent_slug: null,
    sort_order: 34,
    description: "Singles-friendly dance classes, studios and social dance lessons.",
    seo_intro: "Dance classes give singles a practical way to move, learn and meet people without needing to arrive with a partner.",
    seo_title: "Dance Classes for Singles Australia | Events4Singles",
    seo_description: "Find singles-friendly dance classes, salsa, bachata, ballroom, swing and social dance lessons in Australia.",
    hero_image_url: "/images/categories/heroes/dance-classes.webp",
  },
  {
    slug: "dance_party_clubs",
    label: "Dance Party Clubs",
    parent_slug: null,
    sort_order: 36,
    description: "Dance parties, music nights and social club events for singles.",
    seo_intro: "Dance party clubs bring together music, movement and social energy for singles who want a lively night out.",
    seo_title: "Dance Party Clubs Australia | Events4Singles",
    seo_description: "Find dance party clubs, social dance nights and music events for singles in Australia.",
    hero_image_url: "/images/categories/heroes/dance-party-clubs.webp",
  },
  {
    slug: "nightclubs",
    label: "Nightclubs",
    parent_slug: null,
    sort_order: 38,
    description: "Late-night venues and social dance floors for singles.",
    seo_intro: "Nightclub listings help singles find venues, nights and social dance floors with a stronger going-out energy.",
    seo_title: "Nightclubs for Singles Australia | Events4Singles",
    seo_description: "Find nightclubs, dance floors and nightlife venues for singles around Australia.",
    hero_image_url: "/images/categories/heroes/nightclubs.webp",
  },
  {
    slug: "adventure_for_singles",
    label: "Adventure for Singles",
    parent_slug: null,
    sort_order: 40,
    description: "Sport, adventure, outdoor activities and active days out for singles who prefer doing something together.",
    seo_intro: "Adventure for singles brings sport, active outings and outdoor experiences into one place for people who would rather meet while moving, exploring or sharing something memorable.",
    seo_title: "Adventure, Sport and Outdoor Activities for Singles Australia | Events4Singles",
    seo_description: "Find sport, adventure activities, outdoor experiences and active events for singles in Australia.",
    hero_image_url: "/images/categories/heroes/adventure-for-singles.webp",
    aliases: ["sport_adventure"],
  },
  {
    slug: "cruises4singles",
    label: "Cruises for Singles",
    parent_slug: null,
    sort_order: 41,
    description: "Social cruises and outings on the water with room to mingle.",
    seo_intro: "Cruises for singles offer an easy shared setting for conversation, scenery and social time on the water.",
    seo_title: "Cruises for Singles Australia | Events4Singles",
    seo_description: "Find singles cruises, harbour cruises and social cruise experiences around Australia.",
    hero_image_url: "/images/categories/heroes/cruises4singles.webp",
  },
  {
    slug: "solo_travel",
    label: "Solo Travel",
    parent_slug: null,
    sort_order: 44,
    description: "Solo travel, tours for singles, group trips and getaways built for independent guests.",
    seo_intro: "Solo travel listings help independent singles find tours, group trips and getaways designed to feel comfortable when you are travelling on your own but still want shared company.",
    seo_title: "Solo Travel and Tours for Singles Australia | Events4Singles",
    seo_description: "Find solo travel, tours for singles, group trips and getaway options for Australian singles.",
    hero_image_url: "/images/categories/heroes/tours4singles.webp",
    aliases: ["travel_for_singles", "tours4singles"],
  },
  {
    slug: "social_walks",
    label: "Social Walks",
    parent_slug: null,
    sort_order: 42,
    description: "Low-pressure walks and outdoor catch-ups with easy conversation.",
    seo_intro: "Social walks give singles a relaxed way to meet people while getting outside and doing something simple together.",
    seo_title: "Social Walks for Singles Australia | Events4Singles",
    seo_description: "Find social walks, walking groups and low-pressure outdoor events for singles.",
    hero_image_url: "/images/categories/heroes/social-walks.webp",
    aliases: ["walks4singles"],
  },
  {
    slug: "life_coaches",
    label: "Life Coaches",
    parent_slug: null,
    sort_order: 56,
    description: "Guidance for confidence, goals and personal direction.",
    seo_intro: "Life coaches can help singles build confidence, reset direction and make clearer choices in life and relationships.",
    seo_title: "Life Coaches for Singles Australia | Events4Singles",
    seo_description: "Find life coaches, confidence coaching and personal direction support for Australian singles.",
    hero_image_url: "/images/categories/heroes/life-coaches.webp",
  },
  {
    slug: "dating_coaches",
    label: "Dating Coaches",
    parent_slug: null,
    sort_order: 58,
    description: "Dating-specific support for confidence, profiles and relationship readiness.",
    seo_intro: "Dating coaches can help singles improve confidence, communication, profile strategy and the way they approach modern dating.",
    seo_title: "Dating Coaches Australia | Events4Singles",
    seo_description: "Find dating coaches and dating confidence support for Australian singles.",
    hero_image_url: "/images/categories/heroes/dating-coaches.webp",
  },
  {
    slug: "psychology",
    label: "Psychology",
    parent_slug: null,
    sort_order: 60,
    description: "Professional support for emotional wellbeing, patterns and relationship readiness.",
    seo_intro: "Psychology services can support singles with wellbeing, recovery, confidence and healthier relationship patterns.",
    seo_title: "Psychology for Singles Australia | Events4Singles",
    seo_description: "Find psychology and emotional wellbeing support for singles in Australia.",
    hero_image_url: "/images/categories/heroes/psychology.webp",
  },
  {
    slug: "healing_and_happiness",
    label: "Healing & Happiness",
    parent_slug: null,
    sort_order: 62,
    description: "Wellbeing services for renewal, confidence and balance.",
    seo_intro: "Healing and happiness services support singles who want more steadiness, renewal and wellbeing in daily life.",
    seo_title: "Healing & Happiness for Singles Australia | Events4Singles",
    seo_description: "Find wellbeing, healing and happiness services for Australian singles.",
    hero_image_url: "/images/categories/heroes/healing-and-happiness.webp",
  },
  {
    slug: "retreats_for_singles",
    label: "Retreats for Singles",
    parent_slug: null,
    sort_order: 64,
    description: "Retreats, reset weekends and reflective escapes for singles.",
    seo_intro: "Retreats for singles create space to reset, reflect and reconnect with yourself among people in a similar season.",
    seo_title: "Retreats for Singles Australia | Events4Singles",
    seo_description: "Find retreats, reset weekends and personal growth escapes for singles in Australia.",
    hero_image_url: "/images/categories/heroes/retreats-for-singles.webp",
  },
  {
    slug: "seminars",
    label: "Seminars & Workshops",
    parent_slug: null,
    sort_order: 66,
    description: "Learning experiences for personal, social and relationship growth.",
    seo_intro: "Seminars and workshops give singles structured ways to learn, grow and build confidence around connection.",
    seo_title: "Seminars & Workshops for Singles Australia | Events4Singles",
    seo_description: "Find seminars, workshops and personal development events for singles in Australia.",
    hero_image_url: "/images/categories/heroes/seminars.webp",
  },
  {
    slug: "fitness4singles",
    label: "Fitness for Singles",
    parent_slug: null,
    sort_order: 68,
    description: "Movement, health and energy with social possibility.",
    seo_intro: "Fitness for singles is a practical way to build health and confidence while meeting people through shared activity.",
    seo_title: "Fitness for Singles Australia | Events4Singles",
    seo_description: "Find fitness classes, group exercise and active wellbeing options for singles in Australia.",
    hero_image_url: "/images/categories/heroes/fitness4singles.webp",
  },
  {
    slug: "yoga_classes",
    label: "Yoga Classes",
    parent_slug: null,
    sort_order: 70,
    description: "Yoga classes for calm, strength and self-connection.",
    seo_intro: "Yoga classes help singles build calm, strength and a steadier relationship with their own wellbeing.",
    seo_title: "Yoga Classes for Singles Australia | Events4Singles",
    seo_description: "Find yoga classes, wellness sessions and mindful movement options for singles in Australia.",
    hero_image_url: "/images/categories/heroes/yoga-classes.webp",
  },
  {
    slug: "image_and_photography",
    label: "Image & Photography",
    parent_slug: null,
    sort_order: 72,
    description: "Presentation, styling and photography support for confidence and profiles.",
    seo_intro: "Image and photography services can help singles show up with more confidence in dating, profiles and everyday life.",
    seo_title: "Image & Photography for Singles Australia | Events4Singles",
    seo_description: "Find image, styling and photography services for Australian singles.",
    hero_image_url: "/images/categories/heroes/image-and-photography.webp",
  },
  {
    slug: "dating_profile_photography",
    label: "Dating Profile Photography",
    parent_slug: null,
    sort_order: 74,
    description: "Profile-focused portraits that help singles show up naturally online.",
    seo_intro: "Dating profile photography is for singles who want current, natural portraits for dating apps, profiles and first impressions.",
    seo_title: "Dating Profile Photography Australia | Events4Singles",
    seo_description: "Find dating profile photography and portrait services for Australian singles.",
    hero_image_url: "/images/categories/heroes/dating-profile-photography.webp",
  },
  {
    slug: "singles_health",
    label: "Singles Health",
    parent_slug: null,
    sort_order: 76,
    description: "Health-focused support for a stronger everyday life.",
    seo_intro: "Singles health listings bring together services that support wellbeing, confidence and a stronger daily foundation.",
    seo_title: "Singles Health Australia | Events4Singles",
    seo_description: "Find health and wellbeing services for Australian singles.",
    hero_image_url: "/images/categories/heroes/singles-health.webp",
  },
];

export const CANONICAL_CATEGORY_BY_SLUG = new Map(
  CANONICAL_CATEGORY_REPAIRS.map((category) => [category.slug, category]),
);

const CATEGORY_REDIRECT_TARGETS = new Map([
  ["dinner_for_six", "dinner_parties"],
  ["sport_adventure", "adventure_for_singles"],
  ["tours4singles", "solo_travel"],
  ["travel_for_singles", "solo_travel"],
  ["walks4singles", "social_walks"],
]);

export function categoryRedirectTarget(categorySlug: string): string | undefined {
  return CATEGORY_REDIRECT_TARGETS.get(categorySlug);
}

export const EVENT_CATEGORY_OPTIONS = [
  "speed_dating",
  "singles_mixers",
  "dinner_parties",
  "intro_agencies",
  "online_dating",
  "christian_singles",
  "lgbtqia_singles_events",
  "mature_dating_events",
  "social_clubs",
  "dance_classes",
  "dance_party_clubs",
  "nightclubs",
  "adventure_for_singles",
  "cruises4singles",
  "social_walks",
  "solo_travel",
  "life_coaches",
  "dating_coaches",
  "psychology",
  "healing_and_happiness",
  "retreats_for_singles",
  "seminars",
  "fitness4singles",
  "yoga_classes",
  "image_and_photography",
  "dating_profile_photography",
  "singles_health",
] as const;

export function canonicalCategoryToCategory(category: CanonicalCategory, listingCount = 0): Category {
  return {
    slug: category.slug,
    label: category.label,
    parent_slug: category.parent_slug,
    description: category.description,
    seo_title: category.seo_title,
    seo_description: category.seo_description,
    seo_intro: category.seo_intro,
    hero_image_url: category.hero_image_url,
    listing_count: listingCount,
  };
}

export function categoryScopeAliases(categorySlug: string): string[] {
  const category = CANONICAL_CATEGORY_BY_SLUG.get(categorySlug);
  return category?.aliases ?? [];
}
