const CATEGORY_CARD_IMAGES: Record<string, string> = {
  "adventure-for-singles": "/images/categories/optimized/adventure-for-singles.webp",
  "beauty-for-singles": "/images/categories/optimized/beauty-for-singles.webp",
  "comedians": "/images/categories/optimized/comedians.webp",
  "cruises4singles": "/images/categories/optimized/cruises4singles.webp",
  "dance-ballroom-style": "/images/categories/optimized/dance-ballroom-style.webp",
  "dance-bachata": "/images/categories/optimized/dance-bachata.webp",
  "dance-ceroc": "/images/categories/optimized/dance-ceroc.webp",
  "dance-classes": "/images/categories/optimized/dance-classes.webp",
  "dance-fitness-and-health": "/images/categories/optimized/dance-fitness-and-health.webp",
  "dance-latin-style": "/images/categories/optimized/dance-latin-style.webp",
  "dance-line-dancing": "/images/categories/optimized/dance-line-dancing.webp",
  "dance-modern-style": "/images/categories/optimized/dance-modern-style.webp",
  "dance-party-clubs": "/images/categories/optimized/dance-party-clubs.webp",
  "dance-salsa": "/images/categories/optimized/dance-salsa.webp",
  "dance-styles": "/images/categories/optimized/dance-styles.webp",
  "dance-swing": "/images/categories/optimized/dance-swing.webp",
  "dance-tango": "/images/categories/optimized/dance-tango.webp",
  "dance-teachers": "/images/categories/optimized/dance-teachers.webp",
  "dating-coaches": "/images/categories/optimized/dating-coaches.webp",
  "dating-profile-photography": "/images/categories/optimized/dating-profile-photography.webp",
  "dinner-for-six": "/images/categories/optimized/dinner-for-six.webp",
  "dinner-parties": "/images/categories/optimized/dinner-parties.webp",
  "finance-mortgage": "/images/categories/optimized/finance-mortgage.webp",
  "fitness4singles": "/images/categories/optimized/fitness4singles.webp",
  "function-centres": "/images/categories/optimized/function-centres.webp",
  "golf": "/images/categories/optimized/golf.webp",
  "healing-and-happiness": "/images/categories/optimized/healing-and-happiness.webp",
  "houseparties": "/images/categories/optimized/houseparties.webp",
  "image-and-photography": "/images/categories/optimized/image-and-photography.webp",
  "intro-agencies": "/images/categories/optimized/intro-agencies.webp",
  "jazz": "/images/categories/optimized/jazz.webp",
  "lgbtqia-singles-events": "/images/categories/optimized/lgbtqia-singles-events.webp",
  "life-coaches": "/images/categories/optimized/life-coaches.webp",
  "lotto4singles": "/images/categories/optimized/lotto4singles.webp",
  "mature-dating-events": "/images/categories/optimized/mature-dating-events.webp",
  "nightclubs": "/images/categories/optimized/nightclubs.webp",
  "online-dating": "/images/categories/optimized/online-dating.webp",
  "online-dating-international": "/images/categories/optimized/online-dating-international.webp",
  "psychics4singles": "/images/categories/optimized/psychics4singles.webp",
  "psychology": "/images/categories/optimized/psychology.webp",
  "restaurants-cafes": "/images/categories/optimized/restaurants-cafes.webp",
  "retreats-for-singles": "/images/categories/optimized/retreats-for-singles.webp",
  "seminars": "/images/categories/optimized/seminars.webp",
  "singles-health": "/images/categories/optimized/singles-health.webp",
  "singles-mixers": "/images/categories/optimized/singles-mixers.webp",
  "christian-singles": "/images/categories/optimized/christian-singles.webp",
  "singles-products": "/images/categories/optimized/singles-products.webp",
  "sms-phone-dating": "/images/categories/optimized/sms-phone-dating.webp",
  "social-clubs": "/images/categories/optimized/social-clubs.webp",
  "social-walks": "/images/categories/optimized/social-walks.webp",
  "solo-travel": "/images/categories/optimized/solo-travel.webp",
  "speed-dating": "/images/categories/optimized/speed-dating.webp",
  "sport-adventure": "/images/categories/optimized/sport-adventure.webp",
  "tours4singles": "/images/categories/optimized/tours4singles.webp",
  "travel-for-singles": "/images/categories/optimized/travel-for-singles.webp",
  "walks4singles": "/images/categories/optimized/walks4singles.webp",
  "wineries4singles": "/images/categories/optimized/wineries4singles.webp",
  "yoga-classes": "/images/categories/optimized/yoga-classes.webp",
};

const CATEGORY_CARD_SUMMARIES: Record<string, string> = {
  "adventure-for-singles": "Outdoor activities and shared experiences with a little momentum.",
  "beauty-for-singles": "Grooming, presentation and confidence services for singles.",
  "comedians": "Comedy nights and lighter social entertainment.",
  "cruises4singles": "Social outings on the water with room to mingle.",
  "dance-ballroom-style": "Classic partner dancing with structure, rhythm and easy social connection.",
  "dance-bachata": "Modern Latin partner dancing with an easy, social rhythm.",
  "dance-ceroc": "Modern partner dancing with an easy social rhythm.",
  "dance-classes": "Learn, move and meet people in a relaxed class setting.",
  "dance-fitness-and-health": "Movement-based classes for energy, confidence and wellbeing.",
  "dance-latin-style": "Latin dance classes and socials with warmth, rhythm and connection.",
  "dance-line-dancing": "No-partner group dancing with repeatable steps and easy confidence.",
  "dance-modern-style": "Contemporary movement classes with expressive, social energy.",
  "dance-party-clubs": "Music, movement and social nights with energy.",
  "dance-salsa": "Latin dance classes and salsa social nights.",
  "dance-styles": "Different dance styles for singles who want to explore what fits.",
  "dance-swing": "Playful swing and jive classes with upbeat social energy.",
  "dance-tango": "Elegant tango classes, socials and dance communities.",
  "dance-teachers": "Dance instructors and class providers for singles.",
  "dating-coaches": "Dating-specific support for confidence, profiles and relationship readiness.",
  "dating-profile-photography": "Profile-focused portraits that help singles show up naturally.",
  "dinner-for-six": "Smaller hosted meals with easier conversation.",
  "dinner-parties": "Longer conversations over a shared meal.",
  "finance-mortgage": "Money, mortgage and practical support for life planning.",
  "fitness4singles": "Movement, health and energy with social possibility.",
  "function-centres": "Venues and event spaces suited to singles gatherings.",
  "golf": "Golf days, clubs and social rounds for singles.",
  "healing-and-happiness": "Wellbeing services for renewal and balance.",
  "houseparties": "Hosted home-style gatherings and relaxed social nights.",
  "image-and-photography": "Presentation, confidence and profile-ready imagery.",
  "intro-agencies": "Personalised matching and more guided support.",
  "jazz": "Live music nights and jazz venues with social atmosphere.",
  "lgbtqia-singles-events": "Inclusive singles events and social spaces for LGBTQIA+ communities.",
  "life-coaches": "Guidance for goals, confidence and personal direction.",
  "lotto4singles": "Lighthearted prize, lotto and chance-based offers for singles.",
  "mature-dating-events": "Dating experiences for singles later in life.",
  "nightclubs": "Late-night venues and social dance floors.",
  "online-dating": "Digital dating options to support your wider search.",
  "online-dating-international": "International online dating services for singles looking further afield.",
  "psychics4singles": "Intuitive, spiritual and psychic services for singles.",
  "psychology": "Professional support for emotional wellbeing and patterns.",
  "restaurants-cafes": "Dining venues, cafes and social food experiences.",
  "retreats-for-singles": "Retreats, reset weekends and reflective escapes for singles.",
  "seminars": "Learning experiences for personal and social growth.",
  "singles-health": "Health-focused support for a stronger everyday life.",
  "singles-mixers": "Relaxed hosted socials where meeting new people is the point.",
  "christian-singles": "Faith-aligned events, groups and services for Christian singles.",
  "singles-products": "Products, gifts and resources aimed at singles.",
  "sms-phone-dating": "Phone and text-based dating options for low-pressure connection.",
  "social-clubs": "Regular groups and hosted gatherings for singles.",
  "social-walks": "Low-pressure walks and outdoor catch-ups with easy conversation.",
  "solo-travel": "Travel experiences built for independent singles and solo guests.",
  "speed-dating": "Short, hosted introductions with a clear dating purpose.",
  "sport-adventure": "Active events for people who like to do, not just sit.",
  "tours4singles": "Shared trips and discovery with other singles.",
  "travel-for-singles": "Trips and getaways with other singles.",
  "walks4singles": "Easy conversation while exploring local places.",
  "wineries4singles": "Cellar doors, tastings and relaxed vineyard social outings.",
  "yoga-classes": "Calm, strength and self-connection through practice.",
};

const CATEGORY_HERO_IMAGES: Record<string, string> = {
  "adventure-for-singles": "/images/categories/hero/adventure-for-singles.webp",
  "beauty-for-singles": "/images/categories/hero/beauty-for-singles.webp",
  "comedians": "/images/categories/hero/comedians.webp",
  "cruises4singles": "/images/categories/hero/cruises4singles.webp",
  "dance-ballroom-style": "/images/categories/hero/dance-ballroom-style.webp",
  "dance-bachata": "/images/categories/hero/dance-bachata.webp",
  "dance-ceroc": "/images/categories/hero/dance-ceroc.webp",
  "dance-classes": "/images/categories/hero/dance-classes.webp",
  "dance-fitness-and-health": "/images/categories/hero/dance-fitness-and-health.webp",
  "dance-latin-style": "/images/categories/hero/dance-latin-style.webp",
  "dance-line-dancing": "/images/categories/hero/dance-line-dancing.webp",
  "dance-modern-style": "/images/categories/hero/dance-modern-style.webp",
  "dance-party-clubs": "/images/categories/hero/dance-party-clubs.webp",
  "dance-salsa": "/images/categories/hero/dance-salsa.webp",
  "dance-styles": "/images/categories/hero/dance-styles.webp",
  "dance-swing": "/images/categories/hero/dance-swing.webp",
  "dance-tango": "/images/categories/hero/dance-tango.webp",
  "dance-teachers": "/images/categories/hero/dance-teachers.webp",
  "dating-coaches": "/images/categories/hero/dating-coaches.webp",
  "dating-profile-photography": "/images/categories/hero/dating-profile-photography.webp",
  "dinner-for-six": "/images/categories/hero/dinner-for-six.webp",
  "dinner-parties": "/images/categories/hero/dinner-parties.webp",
  "finance-mortgage": "/images/categories/hero/finance-mortgage.webp",
  "fitness4singles": "/images/categories/hero/fitness4singles.webp",
  "function-centres": "/images/categories/hero/function-centres.webp",
  "golf": "/images/categories/hero/golf.webp",
  "healing-and-happiness": "/images/categories/hero/healing-and-happiness.webp",
  "houseparties": "/images/categories/hero/houseparties.webp",
  "image-and-photography": "/images/categories/hero/image-and-photography.webp",
  "intro-agencies": "/images/categories/hero/intro-agencies.webp",
  "jazz": "/images/categories/hero/jazz.webp",
  "lgbtqia-singles-events": "/images/categories/hero/lgbtqia-singles-events.webp",
  "life-coaches": "/images/categories/hero/life-coaches.webp",
  "lotto4singles": "/images/categories/hero/lotto4singles.webp",
  "mature-dating-events": "/images/categories/hero/mature-dating-events.webp",
  "nightclubs": "/images/categories/hero/nightclubs.webp",
  "online-dating": "/images/categories/hero/online-dating.webp",
  "online-dating-international": "/images/categories/hero/online-dating-international.webp",
  "psychics4singles": "/images/categories/hero/psychics4singles.webp",
  "psychology": "/images/categories/hero/psychology.webp",
  "restaurants-cafes": "/images/categories/hero/restaurants-cafes.webp",
  "retreats-for-singles": "/images/categories/hero/retreats-for-singles.webp",
  "seminars": "/images/categories/hero/seminars.webp",
  "singles-health": "/images/categories/hero/singles-health.webp",
  "singles-mixers": "/images/categories/hero/singles-mixers.webp",
  "christian-singles": "/images/categories/hero/christian-singles.webp",
  "singles-products": "/images/categories/hero/singles-products.webp",
  "sms-phone-dating": "/images/categories/hero/sms-phone-dating.webp",
  "social-clubs": "/images/categories/hero/social-clubs.webp",
  "social-walks": "/images/categories/hero/social-walks.webp",
  "solo-travel": "/images/categories/hero/solo-travel.webp",
  "speed-dating": "/images/categories/hero/speed-dating.webp",
  "sport-adventure": "/images/categories/hero/sport-adventure.webp",
  "tours4singles": "/images/categories/hero/tours4singles.webp",
  "travel-for-singles": "/images/categories/hero/travel-for-singles.webp",
  "walks4singles": "/images/categories/hero/walks4singles.webp",
  "wineries4singles": "/images/categories/hero/wineries4singles.webp",
  "yoga-classes": "/images/categories/hero/yoga-classes.webp",
};

export function getCategoryCardImage(slug: string): string | undefined {
  return CATEGORY_CARD_IMAGES[slug.replace(/_/g, "-")];
}

export function getCategoryHeroImage(slug: string): string | undefined {
  return CATEGORY_HERO_IMAGES[slug.replace(/_/g, "-")];
}

export function getCategoryCardSummary(slug: string, fallback?: string | null): string {
  return CATEGORY_CARD_SUMMARIES[slug.replace(/_/g, "-")] ?? fallback ?? "";
}
