const CATEGORY_CARD_IMAGES: Record<string, string> = {
  "adventure-for-singles": "/images/categories/optimized/adventure-for-singles.webp",
  "beauty-for-singles": "/images/categories/optimized/beauty-for-singles.webp",
  "comedians": "/images/categories/optimized/comedians.webp",
  "cruises4singles": "/images/categories/optimized/cruises4singles.webp",
  "dance-ceroc": "/images/categories/optimized/dance-ceroc.webp",
  "dance-classes": "/images/categories/optimized/dance-classes.webp",
  "dance-party-clubs": "/images/categories/optimized/dance-party-clubs.webp",
  "dance-salsa": "/images/categories/optimized/dance-salsa.webp",
  "dance-tango": "/images/categories/optimized/dance-tango.webp",
  "dance-teachers": "/images/categories/optimized/dance-teachers.webp",
  "dinner-for-six": "/images/categories/optimized/dinner-for-six.webp",
  "dinner-parties": "/images/categories/optimized/dinner-parties.webp",
  "finance-mortgage": "/images/categories/optimized/finance-mortgage.webp",
  "fitness4singles": "/images/categories/optimized/fitness4singles.webp",
  "function-centres": "/images/categories/optimized/function-centres.webp",
  "golf": "/images/categories/optimized/golf.webp",
  "healing-and-happiness": "/images/categories/optimized/healing-and-happiness.webp",
  "houseparties": "/images/categories/optimized/houseparties.webp",
  "image-and-photography": "/images/categories/optimized/image-and-photography.webp",
  "intro-agencies": "/images/categories/optimized/intro-agencies.webp",
  "jazz": "/images/categories/optimized/jazz.webp",
  "life-coaches": "/images/categories/optimized/life-coaches.webp",
  "lotto4singles": "/images/categories/optimized/lotto4singles.webp",
  "mature-dating-events": "/images/categories/optimized/mature-dating-events.webp",
  "nightclubs": "/images/categories/optimized/nightclubs.webp",
  "online-dating": "/images/categories/optimized/online-dating.webp",
  "psychics4singles": "/images/categories/optimized/psychics4singles.webp",
  "psychology": "/images/categories/optimized/psychology.webp",
  "restaurants-cafes": "/images/categories/optimized/restaurants-cafes.webp",
  "retreats-for-singles": "/images/categories/optimized/retreats-for-singles.webp",
  "seminars": "/images/categories/optimized/seminars.webp",
  "singles-health": "/images/categories/optimized/singles-health.webp",
  "singles-products": "/images/categories/optimized/singles-products.webp",
  "sms-phone-dating": "/images/categories/optimized/sms-phone-dating.webp",
  "social-clubs": "/images/categories/optimized/social-clubs.webp",
  "speed-dating": "/images/categories/optimized/speed-dating.webp",
  "sport-adventure": "/images/categories/optimized/sport-adventure.webp",
  "tours4singles": "/images/categories/optimized/tours4singles.webp",
  "travel-for-singles": "/images/categories/optimized/travel-for-singles.webp",
  "walks4singles": "/images/categories/optimized/walks4singles.webp",
  "wineries4singles": "/images/categories/optimized/wineries4singles.webp",
  "yoga-classes": "/images/categories/optimized/yoga-classes.webp",
};

const CATEGORY_CARD_SUMMARIES: Record<string, string> = {
  "adventure-for-singles": "Outdoor activities and shared experiences with a little momentum.",
  "beauty-for-singles": "Grooming, presentation and confidence services for singles.",
  "comedians": "Comedy nights and lighter social entertainment.",
  "cruises4singles": "Social outings on the water with room to mingle.",
  "dance-ceroc": "Modern partner dancing with an easy social rhythm.",
  "dance-classes": "Learn, move and meet people in a relaxed class setting.",
  "dance-party-clubs": "Music, movement and social nights with energy.",
  "dance-salsa": "Latin dance classes and salsa social nights.",
  "dance-tango": "Elegant tango classes, socials and dance communities.",
  "dance-teachers": "Dance instructors and class providers for singles.",
  "dinner-for-six": "Smaller hosted meals with easier conversation.",
  "dinner-parties": "Longer conversations over a shared meal.",
  "finance-mortgage": "Money, mortgage and practical support for life planning.",
  "fitness4singles": "Movement, health and energy with social possibility.",
  "function-centres": "Venues and event spaces suited to singles gatherings.",
  "golf": "Golf days, clubs and social rounds for singles.",
  "healing-and-happiness": "Wellbeing services for renewal and balance.",
  "houseparties": "Hosted home-style gatherings and relaxed social nights.",
  "image-and-photography": "Presentation, confidence and profile-ready imagery.",
  "intro-agencies": "Personalised matching and more guided support.",
  "jazz": "Live music nights and jazz venues with social atmosphere.",
  "life-coaches": "Guidance for goals, confidence and personal direction.",
  "lotto4singles": "Lighthearted prize, lotto and chance-based offers for singles.",
  "mature-dating-events": "Dating experiences for singles later in life.",
  "nightclubs": "Late-night venues and social dance floors.",
  "online-dating": "Digital dating options to support your wider search.",
  "psychics4singles": "Intuitive, spiritual and psychic services for singles.",
  "psychology": "Professional support for emotional wellbeing and patterns.",
  "restaurants-cafes": "Dining venues, cafes and social food experiences.",
  "retreats-for-singles": "Wellbeing escapes, reset weekends and calmer ways to meet.",
  "seminars": "Learning experiences for personal and social growth.",
  "singles-health": "Health-focused support for a stronger everyday life.",
  "singles-products": "Products, gifts and resources aimed at singles.",
  "sms-phone-dating": "Phone and text-based dating options for low-pressure connection.",
  "social-clubs": "Regular groups and hosted gatherings for singles.",
  "speed-dating": "Short, hosted introductions with a clear dating purpose.",
  "sport-adventure": "Active events for people who like to do, not just sit.",
  "tours4singles": "Shared trips and discovery with other singles.",
  "travel-for-singles": "Trips and getaways with other singles.",
  "walks4singles": "Easy conversation while exploring local places.",
  "wineries4singles": "Cellar doors, tastings and relaxed vineyard social outings.",
  "yoga-classes": "Calm, strength and self-connection through practice.",
};

export function getCategoryCardImage(slug: string): string | undefined {
  return CATEGORY_CARD_IMAGES[slug];
}

export function getCategoryCardSummary(slug: string, fallback?: string | null): string {
  return CATEGORY_CARD_SUMMARIES[slug] ?? fallback ?? "";
}
