import type { PublicEvent } from "@/lib/data";

export const HOMEPAGE_PLACEHOLDER_EVENTS = [
  { id: "p1", title: "Speed Dating Sydney — 30s & 40s", starts_at: "2026-09-06T19:00:00+10:00", ends_at: null, timezone: "Australia/Sydney", venue_name: "The Establishment Bar", address: null, suburb: "Sydney CBD", city: "sydney", state: "NSW", price_min: 3500, price_max: null, image_url: "/images/site/home/category-cards/home-cat-speed-dating.webp", source: "admin", source_url: null, ticket_url: null, description: "Fast-paced fun for Sydney singles in their 30s and 40s. Seven-minute dates, great drinks.", category: "speed_dating" },
  { id: "p2", title: "Singles Dinner Party Melbourne", starts_at: "2026-09-13T19:30:00+10:00", ends_at: null, timezone: "Australia/Melbourne", venue_name: "Cumulus Inc.", address: null, suburb: "Flinders Lane", city: "melbourne", state: "VIC", price_min: 9500, price_max: null, image_url: "/images/site/home/category-cards/home-cat-dinner-parties.webp", source: "admin", source_url: null, ticket_url: null, description: "Long-table dinner for 20 Melbourne professionals. Matched seating, three courses, no awkward silences.", category: "dinner_parties" },
  { id: "p3", title: "Salsa Social — Singles Night Brisbane", starts_at: "2026-09-20T18:00:00+10:00", ends_at: null, timezone: "Australia/Brisbane", venue_name: "Cloudland", address: null, suburb: "Fortitude Valley", city: "brisbane", state: "QLD", price_min: 2500, price_max: null, image_url: "/images/site/home/category-cards/home-cat-activities.webp", source: "admin", source_url: null, ticket_url: null, description: "Beginner salsa lesson followed by a social dance floor open to all singles.", category: "dance_classes" },
  { id: "p4", title: "Speed Dating Perth — 20s & 30s", starts_at: "2026-09-27T19:00:00+08:00", ends_at: null, timezone: "Australia/Perth", venue_name: "The Rooftop Bar", address: null, suburb: "Northbridge", city: "perth", state: "WA", price_min: 3000, price_max: null, image_url: "/images/site/home/category-cards/home-cat-speed-dating.webp", source: "admin", source_url: null, ticket_url: null, description: "Perth's most popular speed dating night for singles in their 20s and 30s.", category: "speed_dating" },
  { id: "p5", title: "Mixer Night Adelaide", starts_at: "2026-10-04T18:30:00+09:30", ends_at: null, timezone: "Australia/Adelaide", venue_name: "Press Food & Wine", address: null, suburb: "Adelaide CBD", city: "adelaide", state: "SA", price_min: 2000, price_max: null, image_url: "/images/site/home/category-cards/home-cat-mixers.webp", source: "admin", source_url: null, ticket_url: null, description: "Relaxed after-work mixer in Adelaide's best wine bar. No awkward games, just great people.", category: "social_clubs" },
  { id: "p6", title: "Premium Dinner Party Sydney", starts_at: "2026-10-11T19:00:00+10:00", ends_at: null, timezone: "Australia/Sydney", venue_name: "Quay Restaurant", address: null, suburb: "The Rocks", city: "sydney", state: "NSW", price_min: 14500, price_max: null, image_url: "/images/site/home/category-cards/home-cat-dinner-parties.webp", source: "admin", source_url: null, ticket_url: null, description: "Sydney's most exclusive singles dinner — waterfront views, matched seating, five courses.", category: "dinner_parties" },
  { id: "p7", title: "Speed Dating Melbourne CBD", starts_at: "2026-10-18T19:00:00+10:00", ends_at: null, timezone: "Australia/Melbourne", venue_name: "Taxi Kitchen", address: null, suburb: "Federation Square", city: "melbourne", state: "VIC", price_min: 3500, price_max: null, image_url: "/images/site/home/category-cards/home-cat-speed-dating.webp", source: "admin", source_url: null, ticket_url: null, description: "Melbourne's iconic speed dating night returns with a fresh format and great venue.", category: "speed_dating" },
  { id: "p8", title: "Dance & Social Night — Gold Coast", starts_at: "2026-10-25T18:00:00+10:00", ends_at: null, timezone: "Australia/Brisbane", venue_name: "HOTA", address: null, suburb: "Surfers Paradise", city: "gold_coast", state: "QLD", price_min: 2500, price_max: null, image_url: "/images/site/home/category-cards/home-cat-activities.webp", source: "admin", source_url: null, ticket_url: null, description: "Fun social dancing for Gold Coast singles — no experience needed.", category: "dance_classes" },
] as PublicEvent[];
