import type { NextConfig } from "next";
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";

// Sets up D1/KV/R2 bindings during `next dev` via wrangler's getPlatformProxy.
// Intentionally not awaited — the function handles its own async init.
initOpenNextCloudflareForDev();

const nextConfig: NextConfig = {
  distDir: process.env.E4S_NEXT_DIST_DIR || ".next",
  experimental: process.env.E4S_NEXT_BUILD_CPUS
    ? { cpus: Number(process.env.E4S_NEXT_BUILD_CPUS) }
    : undefined,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "*.supabase.co", pathname: "/storage/v1/object/public/**" },
    ],
  },
  async headers() {
    // Pages that show different content based on admin cookie must never be cached.
    return [
      {
        source: "/site.css",
        headers: [{ key: "Cache-Control", value: "no-cache, max-age=0, must-revalidate" }],
      },
      {
        source: "/images/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=604800, stale-while-revalidate=86400" }],
      },
      {
        source: "/:path((?!api|admin|portal|media|listing|profile|_next).*)",
        headers: [{ key: "Cache-Control", value: "public, s-maxage=3600, stale-while-revalidate=86400" }],
      },
      {
        source: "/listing/:slug*",
        headers: [{ key: "Cache-Control", value: "private, no-store" }],
      },
      {
        source: "/profile/:id*",
        headers: [{ key: "Cache-Control", value: "private, no-store" }],
      },
    ];
  },
  async redirects() {
    return [
      // ── Internal renames ──────────────────────────────────────────────────
      { source: "/locations", destination: "/cities", permanent: true },
      { source: "/privacy", destination: "/privacy-policy", permanent: true },
      { source: "/terms", destination: "/terms-and-conditions", permanent: true },
      { source: "/event-types", destination: "/categories", permanent: true },

      // ── Static image folder renames ───────────────────────────────────────
      { source: "/images/categories/optimized/:path*", destination: "/images/categories/cards/:path*", permanent: true },
      { source: "/images/categories/hero/:path*", destination: "/images/categories/heroes/:path*", permanent: true },
      { source: "/images/cities/source/:path*", destination: "/images/cities/heroes/:path*", permanent: true },
      { source: "/images/cities/optimized/:path*", destination: "/images/cities/heroes/:path*", permanent: true },
      { source: "/images/cities/hero/:path*", destination: "/images/cities/heroes/:path*", permanent: true },
      { source: "/images/optimized/home-cat-activities.webp", destination: "/images/site/home/category-cards/home-cat-activities.webp", permanent: true },
      { source: "/images/optimized/home-cat-cruises.webp", destination: "/images/site/home/category-cards/home-cat-cruises.webp", permanent: true },
      { source: "/images/optimized/home-cat-dinner-parties.webp", destination: "/images/site/home/category-cards/home-cat-dinner-parties.webp", permanent: true },
      { source: "/images/optimized/home-cat-mixers.webp", destination: "/images/site/home/category-cards/home-cat-mixers.webp", permanent: true },
      { source: "/images/optimized/home-cat-speed-dating.webp", destination: "/images/site/home/category-cards/home-cat-speed-dating.webp", permanent: true },
      { source: "/images/optimized/home-cat-sport.webp", destination: "/images/site/home/category-cards/home-cat-sport.webp", permanent: true },
      { source: "/images/optimized/home-cat-travel.webp", destination: "/images/site/home/category-cards/home-cat-travel.webp", permanent: true },
      { source: "/images/optimized/home-cat-walks.webp", destination: "/images/site/home/category-cards/home-cat-walks.webp", permanent: true },
      { source: "/images/optimized/home-cat-yoga.webp", destination: "/images/site/home/category-cards/home-cat-yoga.webp", permanent: true },
      { source: "/images/optimized/home-city-adelaide.webp", destination: "/images/site/home/city-cards/home-city-adelaide.webp", permanent: true },
      { source: "/images/optimized/home-city-brisbane.webp", destination: "/images/site/home/city-cards/home-city-brisbane.webp", permanent: true },
      { source: "/images/optimized/home-city-byron-bay.webp", destination: "/images/site/home/city-cards/home-city-byron-bay.webp", permanent: true },
      { source: "/images/optimized/home-city-cairns.webp", destination: "/images/site/home/city-cards/home-city-cairns.webp", permanent: true },
      { source: "/images/optimized/home-city-canberra.webp", destination: "/images/site/home/city-cards/home-city-canberra.webp", permanent: true },
      { source: "/images/optimized/home-city-central-coast.webp", destination: "/images/site/home/city-cards/home-city-central-coast.webp", permanent: true },
      { source: "/images/optimized/home-city-darwin.webp", destination: "/images/site/home/city-cards/home-city-darwin.webp", permanent: true },
      { source: "/images/optimized/home-city-geelong.webp", destination: "/images/site/home/city-cards/home-city-geelong.webp", permanent: true },
      { source: "/images/optimized/home-city-gold-coast.webp", destination: "/images/site/home/city-cards/home-city-gold-coast.webp", permanent: true },
      { source: "/images/optimized/home-city-hobart.webp", destination: "/images/site/home/city-cards/home-city-hobart.webp", permanent: true },
      { source: "/images/optimized/home-city-melbourne.webp", destination: "/images/site/home/city-cards/home-city-melbourne.webp", permanent: true },
      { source: "/images/optimized/home-city-newcastle.webp", destination: "/images/site/home/city-cards/home-city-newcastle.webp", permanent: true },
      { source: "/images/optimized/home-city-perth.webp", destination: "/images/site/home/city-cards/home-city-perth.webp", permanent: true },
      { source: "/images/optimized/home-city-sunshine-coast.webp", destination: "/images/site/home/city-cards/home-city-sunshine-coast.webp", permanent: true },
      { source: "/images/optimized/home-city-sydney.webp", destination: "/images/site/home/city-cards/home-city-sydney.webp", permanent: true },
      { source: "/images/optimized/home-city-toowoomba.webp", destination: "/images/site/home/city-cards/home-city-toowoomba.webp", permanent: true },
      { source: "/images/optimized/home-city-wollongong.webp", destination: "/images/site/home/city-cards/home-city-wollongong.webp", permanent: true },

      // ── Category taxonomy refresh ─────────────────────────────────────────
      { source: "/travel-for-singles", destination: "/solo-travel", permanent: true },
      { source: "/travel-for-singles/:city", destination: "/solo-travel/:city", permanent: true },
      { source: "/walks4singles", destination: "/social-walks", permanent: true },
      { source: "/walks4singles/:city", destination: "/social-walks/:city", permanent: true },
      { source: "/lotto4singles", destination: "/dating-resources", permanent: true },
      { source: "/singles-products", destination: "/dating-resources", permanent: true },
      { source: "/special-offers", destination: "/advertise", permanent: true },
      { source: "/singles-news", destination: "/dating-resources", permanent: true },
      { source: "/finance-mortgage", destination: "/life-coaches", permanent: true },
      { source: "/finance-mortgage/:city", destination: "/life-coaches/:city", permanent: true },
      { source: "/golf", destination: "/sport-adventure", permanent: true },
      { source: "/golf/:city", destination: "/sport-adventure/:city", permanent: true },
      { source: "/toastmasters", destination: "/seminars", permanent: true },
      { source: "/toastmasters/:city", destination: "/seminars/:city", permanent: true },
      { source: "/art-galleries", destination: "/social-clubs", permanent: true },
      { source: "/art-galleries/:city", destination: "/social-clubs/:city", permanent: true },
      { source: "/spiritual-path", destination: "/retreats-for-singles", permanent: true },
      { source: "/spiritual-path/:city", destination: "/retreats-for-singles/:city", permanent: true },
      { source: "/sms-phone-dating", destination: "/online-dating", permanent: true },
      { source: "/sms-phone-dating/:city", destination: "/online-dating/:city", permanent: true },

      // ── Legacy category pages (.htm) ──────────────────────────────────────
      { source: "/adventure_for_singles.htm", destination: "/adventure-for-singles", permanent: true },
      { source: "/art_galleries.htm", destination: "/social-clubs", permanent: true },
      { source: "/beauty_for_singles.htm", destination: "/beauty-for-singles", permanent: true },
      { source: "/comedians.htm", destination: "/comedians", permanent: true },
      { source: "/cruises4singles.htm", destination: "/cruises4singles", permanent: true },
      { source: "/dance_ballroom_style.htm", destination: "/dance-classes/ballroom-style", permanent: true },
      { source: "/dance_classes.htm", destination: "/dance-classes", permanent: true },
      { source: "/dance_fitness_and_health.htm", destination: "/dance-classes/fitness-and-health", permanent: true },
      { source: "/dance_latin_style.htm", destination: "/dance-classes/latin-style", permanent: true },
      { source: "/dance_modern_style.htm", destination: "/dance-classes/modern-style", permanent: true },
      { source: "/dance_party_clubs.htm", destination: "/dance-party-clubs", permanent: true },
      { source: "/dance_styles.htm", destination: "/dance-classes/styles", permanent: true },
      { source: "/dance_teachers.htm", destination: "/dance-classes/teachers", permanent: true },
      { source: "/dinner_for_six.htm", destination: "/dinner-for-six", permanent: true },
      { source: "/dinner_parties.htm", destination: "/dinner-parties", permanent: true },
      { source: "/finance_mortgage.htm", destination: "/life-coaches", permanent: true },
      { source: "/fitness4singles.htm", destination: "/fitness4singles", permanent: true },
      { source: "/function_centres.htm", destination: "/function-centres", permanent: true },
      { source: "/golf.htm", destination: "/sport-adventure", permanent: true },
      { source: "/healing_and_happiness.htm", destination: "/dating-resources/wellbeing-and-the-single-life", permanent: true },
      { source: "/houseparties.htm", destination: "/houseparties", permanent: true },
      { source: "/image_and_photography.htm", destination: "/image-and-photography", permanent: true },
      { source: "/intro_agencies.htm", destination: "/intro-agencies", permanent: true },
      { source: "/jazz.htm", destination: "/jazz", permanent: true },
      { source: "/jazz_in_australia.htm", destination: "/jazz", permanent: true },
      { source: "/jazz4singles.htm", destination: "/jazz", permanent: true },
      { source: "/life_coaches.htm", destination: "/life-coaches", permanent: true },
      { source: "/lotto4singles.htm", destination: "/dating-resources", permanent: true },
      { source: "/mature_dating_events.htm", destination: "/mature-dating-events", permanent: true },
      { source: "/nightclubs.htm", destination: "/nightclubs", permanent: true },
      { source: "/online_dating.htm", destination: "/online-dating", permanent: true },
      { source: "/online_dating_int.htm", destination: "/online-dating-international", permanent: true },
      { source: "/online_dating_intenational.htm", destination: "/online-dating-international", permanent: true },
      { source: "/psychics4singles.htm", destination: "/psychics4singles", permanent: true },
      { source: "/psychology.htm", destination: "/dating-resources/wellbeing-and-the-single-life", permanent: true },
      { source: "/restaurants_cafes.htm", destination: "/restaurants-cafes", permanent: true },
      { source: "/retreats_for_singles.htm", destination: "/retreats-for-singles", permanent: true },
      { source: "/seminars.htm", destination: "/seminars", permanent: true },
      { source: "/singles_health.htm", destination: "/singles-health", permanent: true },
      { source: "/singles_news.htm", destination: "/dating-resources", permanent: true },
      { source: "/singles_products.htm", destination: "/dating-resources", permanent: true },
      { source: "/sms-phone-dating.htm", destination: "/online-dating", permanent: true },
      { source: "/social_clubs.htm", destination: "/social-clubs", permanent: true },
      { source: "/speed_dating.htm", destination: "/speed-dating", permanent: true },
      { source: "/special_offers.htm", destination: "/advertise", permanent: true },
      { source: "/spiritual_path.htm", destination: "/retreats-for-singles", permanent: true },
      { source: "/sport_adventure.htm", destination: "/sport-adventure", permanent: true },
      { source: "/toastmasters.htm", destination: "/seminars", permanent: true },
      { source: "/tours4singles.htm", destination: "/tours4singles", permanent: true },
      { source: "/travel_for_singles.htm", destination: "/solo-travel", permanent: true },
      { source: "/walks4singles.htm", destination: "/social-walks", permanent: true },
      { source: "/wineries4singles.htm", destination: "/wineries4singles", permanent: true },
      { source: "/yoga_classes.htm", destination: "/yoga-classes", permanent: true },

      // ── Legacy city-variant pages (.htm) ─────────────────────────────────
      { source: "/dance_classes_adelaide.htm", destination: "/dance-classes/adelaide", permanent: true },
      { source: "/dance_classes_brisbane.htm", destination: "/dance-classes/brisbane", permanent: true },
      { source: "/dance_classes_canberra.htm", destination: "/dance-classes/canberra", permanent: true },
      { source: "/dance_classes_melbourne.htm", destination: "/dance-classes/melbourne", permanent: true },
      { source: "/dance_classes_perth.htm", destination: "/dance-classes/perth", permanent: true },
      { source: "/dance_classes_sydney.htm", destination: "/dance-classes/sydney", permanent: true },
      { source: "/dance_party_clubs_adelaide.htm", destination: "/dance-party-clubs/adelaide", permanent: true },
      { source: "/dance_party_clubs_melbourne.htm", destination: "/dance-party-clubs/melbourne", permanent: true },
      { source: "/dance_party_clubs_perth.htm", destination: "/dance-party-clubs/perth", permanent: true },
      { source: "/dance_party_clubs_sydney.htm", destination: "/dance-party-clubs/sydney", permanent: true },
      { source: "/dinner_for_six_adelaide.htm", destination: "/dinner-for-six/adelaide", permanent: true },
      { source: "/dinner_for_six_brisbane.htm", destination: "/dinner-for-six/brisbane", permanent: true },
      { source: "/dinner_for_six_canberra.htm", destination: "/dinner-for-six/canberra", permanent: true },
      { source: "/dinner_for_six_darwin.htm", destination: "/dinner-for-six/darwin", permanent: true },
      { source: "/dinner_for_six_gold_coast.htm", destination: "/dinner-for-six/gold-coast", permanent: true },
      { source: "/dinner_for_six_hobart.htm", destination: "/dinner-for-six/hobart", permanent: true },
      { source: "/dinner_for_six_melbourne.htm", destination: "/dinner-for-six/melbourne", permanent: true },
      { source: "/dinner_for_six_perth.htm", destination: "/dinner-for-six/perth", permanent: true },
      { source: "/dinner_for_six_sydney.htm", destination: "/dinner-for-six/sydney", permanent: true },
      { source: "/dinner_parties_adelaide.htm", destination: "/dinner-parties/adelaide", permanent: true },
      { source: "/dinner_parties_brisbane.htm", destination: "/dinner-parties/brisbane", permanent: true },
      { source: "/dinner_parties_canberra.htm", destination: "/dinner-parties/canberra", permanent: true },
      { source: "/dinner_parties_darwin.htm", destination: "/dinner-parties/darwin", permanent: true },
      { source: "/dinner_parties_hobart.htm", destination: "/dinner-parties/hobart", permanent: true },
      { source: "/dinner_parties_melbourne.htm", destination: "/dinner-parties/melbourne", permanent: true },
      { source: "/dinner_parties_perth.htm", destination: "/dinner-parties/perth", permanent: true },
      { source: "/dinner_parties_sydney.htm", destination: "/dinner-parties/sydney", permanent: true },
      { source: "/jazz_adelaide.htm", destination: "/jazz/adelaide", permanent: true },
      { source: "/jazz_brisbane.htm", destination: "/jazz/brisbane", permanent: true },
      { source: "/jazz_melbourne.htm", destination: "/jazz/melbourne", permanent: true },
      { source: "/jazz_perth.htm", destination: "/jazz/perth", permanent: true },
      { source: "/jazz_sydney.htm", destination: "/jazz/sydney", permanent: true },
      { source: "/life_coaches_brisbane.htm", destination: "/life-coaches/brisbane", permanent: true },
      { source: "/life_coaches_melbourne.htm", destination: "/life-coaches/melbourne", permanent: true },
      { source: "/life_coaches_sydney.htm", destination: "/life-coaches/sydney", permanent: true },
      { source: "/social_clubs_bris.htm", destination: "/social-clubs/brisbane", permanent: true },
      { source: "/social_clubs_canberra.htm", destination: "/social-clubs/canberra", permanent: true },
      { source: "/social_clubs_darwin.htm", destination: "/social-clubs/darwin", permanent: true },
      { source: "/social_clubs_hobart.htm", destination: "/social-clubs/hobart", permanent: true },
      { source: "/social_clubs_melb.htm", destination: "/social-clubs/melbourne", permanent: true },
      { source: "/social_clubs_perth.htm", destination: "/social-clubs/perth", permanent: true },
      { source: "/social_clubs_syd.htm", destination: "/social-clubs/sydney", permanent: true },
      { source: "/social_clubs_syd1.htm", destination: "/social-clubs/sydney", permanent: true },
      { source: "/social_clubs_sydney.htm", destination: "/social-clubs/sydney", permanent: true },
      { source: "/speed_dating_brisbane.htm", destination: "/speed-dating/brisbane", permanent: true },
      { source: "/speed_dating_melbourne.htm", destination: "/speed-dating/melbourne", permanent: true },
      { source: "/speed_dating_perth.htm", destination: "/speed-dating/perth", permanent: true },
      { source: "/speed_dating_sydney.htm", destination: "/speed-dating/sydney", permanent: true },

      // ── Legacy dance style sub-pages → Dance Classes child routes ────────
      { source: "/dance_ballroomstyle.htm", destination: "/dance-classes/ballroom-style", permanent: true },
      { source: "/dance_classes_ballroom_latin.htm", destination: "/dance-classes/ballroom-style", permanent: true },
      { source: "/dance_classes_ceroc.htm", destination: "/dance-classes/ceroc", permanent: true },
      { source: "/dance_classes_salsa.htm", destination: "/dance-classes/salsa", permanent: true },
      { source: "/dance_classes_styles.htm", destination: "/dance-classes/styles", permanent: true },
      { source: "/dance_classes_swing.htm", destination: "/dance-classes/swing", permanent: true },
      { source: "/dance_classes_tango.htm", destination: "/dance-classes/tango", permanent: true },
      { source: "/dance_classes_whatson.htm", destination: "/dance-classes", permanent: true },
      { source: "/dance_classes_tasmania.htm", destination: "/dance-classes", permanent: true },

      // ── More dance city variants ──────────────────────────────────────────
      { source: "/dance_classes_centralcoast.htm", destination: "/dance-classes/central-coast", permanent: true },
      { source: "/dance_classes_goldcoast.htm", destination: "/dance-classes/gold-coast", permanent: true },
      { source: "/dance_classes_newcastle.htm", destination: "/dance-classes/newcastle", permanent: true },
      { source: "/dance_classes_sunshinecoast.htm", destination: "/dance-classes/sunshine-coast", permanent: true },

      // ── More dinner parties city variants ─────────────────────────────────
      { source: "/dinner_parties_centralcoast.htm", destination: "/dinner-parties/central-coast", permanent: true },
      { source: "/dinner_parties_geelong.htm", destination: "/dinner-parties/geelong", permanent: true },
      { source: "/dinner_parties_goldcoast.htm", destination: "/dinner-parties/gold-coast", permanent: true },
      { source: "/dinner_parties_newcastle.htm", destination: "/dinner-parties/newcastle", permanent: true },
      { source: "/dinner_parties_wollongong.htm", destination: "/dinner-parties/wollongong", permanent: true },

      // ── More social clubs city variants ───────────────────────────────────
      { source: "/social_clubs_adel.htm", destination: "/social-clubs/adelaide", permanent: true },
      { source: "/social_clubs_centralcoast.htm", destination: "/social-clubs/central-coast", permanent: true },
      { source: "/social_clubs_geelong.htm", destination: "/social-clubs/geelong", permanent: true },
      { source: "/social_clubs_goldcoast.htm", destination: "/social-clubs/gold-coast", permanent: true },
      { source: "/social_clubs_newcastle.htm", destination: "/social-clubs/newcastle", permanent: true },

      // ── Misc category variants ────────────────────────────────────────────
      { source: "/jazz_tasmania.htm", destination: "/jazz", permanent: true },
      { source: "/speed_dating2.htm", destination: "/speed-dating", permanent: true },
      { source: "/speed_dating3.htm", destination: "/speed-dating", permanent: true },
      { source: "/love_life_coaches.htm", destination: "/life-coaches", permanent: true },
      { source: "/seminars-dance-of-seduction.htm", destination: "/seminars", permanent: true },

      // ── Site info pages ───────────────────────────────────────────────────
      { source: "/about.htm", destination: "/about", permanent: true },
      { source: "/advertise.htm", destination: "/advertise", permanent: true },
      { source: "/advertise_benefits.htm", destination: "/advertise", permanent: true },
      { source: "/pricing_structure.htm", destination: "/advertise", permanent: true },
      { source: "/contact.htm", destination: "/contact", permanent: true },
      { source: "/terms_of_use.htm", destination: "/terms-and-conditions", permanent: true },

      // ── Dating resources pages ────────────────────────────────────────────
      { source: "/dating_resources_books.htm", destination: "/dating-resources/dating-resource-books", permanent: true },
      { source: "/dating_resources_websites.htm", destination: "/dating-resources/dating-resource-websites", permanent: true },
      { source: "/dating_tips.htm", destination: "/dating-resources/dating-advice", permanent: true },
      { source: "/dating_tips_men.htm", destination: "/dating-resources/dating-tips-for-men", permanent: true },
      { source: "/date_safe.htm", destination: "/dating-resources/dating-safety-checklist", permanent: true },
      { source: "/date_jokes.htm", destination: "/dating-resources", permanent: true },
      { source: "/body_language.htm", destination: "/dating-resources/body-language", permanent: true },
      { source: "/flirting.htm", destination: "/dating-resources/flirting", permanent: true },
      { source: "/flirting_2.htm", destination: "/dating-resources/flirting", permanent: true },
      { source: "/romance.htm", destination: "/dating-resources/finding-romance-after-40", permanent: true },
      { source: "/singlesnews_archive.htm", destination: "/dating-resources", permanent: true },
      { source: "/tips_and_links.htm", destination: "/dating-resources", permanent: true },

      // ── Legacy event calendar pages (.htm) → /events ─────────────────────
      { source: "/adeleventcal.htm", destination: "/events", permanent: true },
      { source: "/briseventcal.htm", destination: "/events", permanent: true },
      { source: "/canberraeventcal.htm", destination: "/events", permanent: true },
      { source: "/cencsteventcal.htm", destination: "/events", permanent: true },
      { source: "/centralcoast_events_calendar.htm", destination: "/events", permanent: true },
      { source: "/goldcsteventcal.htm", destination: "/events", permanent: true },
      { source: "/newceventcal.htm", destination: "/events", permanent: true },
      { source: "/pereventcal.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_country_vic.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_geelong.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_goldcoast.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_melbourne2.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_melbourne3.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_melbourne4.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_newcastle.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_wollongong.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_adelaide.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_brisbane.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_canberra.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_melb.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_melbourne.htm", destination: "/events", permanent: true },
      { source: "/event_calendar_perth.htm", destination: "/events", permanent: true },
      { source: "/events_calendar_central_coast.htm", destination: "/events", permanent: true },
      { source: "/events_central_coast.htm", destination: "/events", permanent: true },
      { source: "/events-byron-bay.htm", destination: "/events", permanent: true },
      { source: "/events_adelaide.htm", destination: "/events", permanent: true },
      { source: "/events_brisbane.htm", destination: "/events", permanent: true },
      { source: "/events_cairns.htm", destination: "/events", permanent: true },
      { source: "/events_canberra.htm", destination: "/events", permanent: true },
      { source: "/events_darwin.htm", destination: "/events", permanent: true },
      { source: "/events_geelong.htm", destination: "/events", permanent: true },
      { source: "/events_gold_coast.htm", destination: "/events", permanent: true },
      { source: "/events_hobart.htm", destination: "/events", permanent: true },
      { source: "/events_melbourne.htm", destination: "/events", permanent: true },
      { source: "/events_melbourne2.htm", destination: "/events", permanent: true },
      { source: "/events_newcastle.htm", destination: "/events", permanent: true },
      { source: "/events_perth.htm", destination: "/events", permanent: true },
      { source: "/events_sunshine_coast.htm", destination: "/events", permanent: true },
      { source: "/events_sutherland_shire.htm", destination: "/events", permanent: true },
      { source: "/events_sydney.htm", destination: "/events", permanent: true },
      { source: "/events_sydney2.htm", destination: "/events", permanent: true },
      { source: "/events_toowoomba.htm", destination: "/events", permanent: true },
      { source: "/events_wollongong.htm", destination: "/events", permanent: true },
    ];
  },
};

export default nextConfig;
