name = "events4singles-v2"
main = "worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
account_id = "77513f974459dd7d8a1183712e0f41fd"

[triggers]
crons = ["0 */4 * * *"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "events4singles"
database_id = "0359c4e2-60ac-4037-8e56-f661971bd31a"
