INSERT OR IGNORE INTO events (
  id, title, slug, description, starts_at, ends_at, timezone,
  venue_name, address, suburb, city, state, price_min, price_max,
  ticket_url, image_url, source, source_id, source_url, category,
  status, submitted_by
) VALUES
('seed_home_p1', 'Speed Dating Sydney — 30s & 40s', 'speed-dating-sydney-30s-40s-seed-home-p1', 'Fast-paced fun for Sydney singles in their 30s and 40s. Seven-minute dates, great drinks.', '2026-09-06T19:00:00+10:00', NULL, 'Australia/Sydney', 'The Establishment Bar', NULL, 'Sydney CBD', 'sydney', 'NSW', 3500, NULL, NULL, '/images/home-cat-speed-dating.jpg', 'admin', 'homepage-placeholder-p1', NULL, 'speed_dating', 'approved', NULL),
('seed_home_p2', 'Singles Dinner Party Melbourne', 'singles-dinner-party-melbourne-seed-home-p2', 'Long-table dinner for 20 Melbourne professionals. Matched seating, three courses, no awkward silences.', '2026-09-13T19:30:00+10:00', NULL, 'Australia/Melbourne', 'Cumulus Inc.', NULL, 'Flinders Lane', 'melbourne', 'VIC', 9500, NULL, NULL, '/images/home-cat-dinner-parties.jpg', 'admin', 'homepage-placeholder-p2', NULL, 'dinner_parties', 'approved', NULL),
('seed_home_p3', 'Salsa Social — Singles Night Brisbane', 'salsa-social-singles-night-brisbane-seed-home-p3', 'Beginner salsa lesson followed by a social dance floor open to all singles.', '2026-09-20T18:00:00+10:00', NULL, 'Australia/Brisbane', 'Cloudland', NULL, 'Fortitude Valley', 'brisbane', 'QLD', 2500, NULL, NULL, '/images/home-cat-activities.jpg', 'admin', 'homepage-placeholder-p3', NULL, 'dance_classes', 'approved', NULL),
('seed_home_p4', 'Speed Dating Perth — 20s & 30s', 'speed-dating-perth-20s-30s-seed-home-p4', 'Perth''s most popular speed dating night for singles in their 20s and 30s.', '2026-09-27T19:00:00+08:00', NULL, 'Australia/Perth', 'The Rooftop Bar', NULL, 'Northbridge', 'perth', 'WA', 3000, NULL, NULL, '/images/home-cat-speed-dating.jpg', 'admin', 'homepage-placeholder-p4', NULL, 'speed_dating', 'approved', NULL),
('seed_home_p5', 'Mixer Night Adelaide', 'mixer-night-adelaide-seed-home-p5', 'Relaxed after-work mixer in Adelaide''s best wine bar. No awkward games, just great people.', '2026-10-04T18:30:00+09:30', NULL, 'Australia/Adelaide', 'Press Food & Wine', NULL, 'Adelaide CBD', 'adelaide', 'SA', 2000, NULL, NULL, '/images/home-cat-mixers.jpg', 'admin', 'homepage-placeholder-p5', NULL, 'social_clubs', 'approved', NULL),
('seed_home_p6', 'Premium Dinner Party Sydney', 'premium-dinner-party-sydney-seed-home-p6', 'Sydney''s most exclusive singles dinner — waterfront views, matched seating, five courses.', '2026-10-11T19:00:00+10:00', NULL, 'Australia/Sydney', 'Quay Restaurant', NULL, 'The Rocks', 'sydney', 'NSW', 14500, NULL, NULL, '/images/home-cat-dinner-parties.jpg', 'admin', 'homepage-placeholder-p6', NULL, 'dinner_parties', 'approved', NULL),
('seed_home_p7', 'Speed Dating Melbourne CBD', 'speed-dating-melbourne-cbd-seed-home-p7', 'Melbourne''s iconic speed dating night returns with a fresh format and great venue.', '2026-10-18T19:00:00+10:00', NULL, 'Australia/Melbourne', 'Taxi Kitchen', NULL, 'Federation Square', 'melbourne', 'VIC', 3500, NULL, NULL, '/images/home-cat-speed-dating.jpg', 'admin', 'homepage-placeholder-p7', NULL, 'speed_dating', 'approved', NULL),
('seed_home_p8', 'Dance & Social Night — Gold Coast', 'dance-social-night-gold-coast-seed-home-p8', 'Fun social dancing for Gold Coast singles — no experience needed.', '2026-10-25T18:00:00+10:00', NULL, 'Australia/Brisbane', 'HOTA', NULL, 'Surfers Paradise', 'gold_coast', 'QLD', 2500, NULL, NULL, '/images/home-cat-activities.jpg', 'admin', 'homepage-placeholder-p8', NULL, 'dance_classes', 'approved', NULL);
