-- Location cleanup sweep: conservative title/source-derived location fixes.
-- Generated by tools/generate-location-cleanup.mjs from a production D1 export.
-- Regions that are not canonical city rows are kept in listings.location, not added as cities.

UPDATE listings SET location_city = 'Adelaide', location_state = 'SA', location = 'Adelaide', updated_at = datetime('now') WHERE id = 575;
UPDATE listings SET location = 'Melbourne', location_city = 'Melbourne', location_state = 'VIC', updated_at = datetime('now') WHERE id = 623;
UPDATE listings SET location_city = 'Cairns', location_state = 'QLD', location = 'Cairns', updated_at = datetime('now') WHERE id = 681;
UPDATE listings SET location = 'Riverina NSW', location_city = 'No Location Review', location_state = '', updated_at = datetime('now') WHERE id = 698;
UPDATE listings SET location = 'South Australia', location_city = 'No Location Review', location_state = '', updated_at = datetime('now') WHERE id = 746;
UPDATE listings SET location_city = 'Byron Bay', location_state = '', location = 'Byron Bay', updated_at = datetime('now') WHERE id = 757;
UPDATE listings SET location = 'Blue Mountains', location_city = 'No Location Review', location_state = '', updated_at = datetime('now') WHERE id = 758;
INSERT INTO listing_placements (listing_id, category_slug, city_slug, sort_order, position_type, is_active) SELECT 575, 'psychology', 'adelaide', 0, 'organic', 1 WHERE EXISTS (SELECT 1 FROM listings WHERE id = 575) AND NOT EXISTS (SELECT 1 FROM listing_placements WHERE listing_id = 575 AND category_slug = 'psychology' AND city_slug = 'adelaide');
INSERT INTO listing_placements (listing_id, category_slug, city_slug, sort_order, position_type, is_active) SELECT 681, 'events', 'cairns', 0, 'organic', 1 WHERE EXISTS (SELECT 1 FROM listings WHERE id = 681) AND NOT EXISTS (SELECT 1 FROM listing_placements WHERE listing_id = 681 AND category_slug = 'events' AND city_slug = 'cairns');
