-- Title/type/location cleanup sweep.
-- Generated by tools/generate-title-field-cleanup.mjs from a production D1 export.
-- Obvious title pollution is moved to the correct field; ambiguous cases stay in the review report.

UPDATE listings SET tagline = 'for Sydney''s Business People', description = 'After Work is Sydney''s most active social club for business people. Members are business owners and professionals. After Work is a modern social club that promotes cocktail evenings, dinners, tours, weekends away, theatre and social events.', updated_at = datetime('now') WHERE id = 19;
UPDATE listings SET title = 'After Work Social Club', tagline = 'for Sydney''s Business People', updated_at = datetime('now') WHERE id = 20;
UPDATE listings SET title = 'Age of Miracles', location = 'Hornsby', updated_at = datetime('now') WHERE id = 22;
UPDATE listings SET title = 'Barbs on the Walk', updated_at = datetime('now') WHERE id = 63;
UPDATE listings SET title = 'Dr. Red Wine', updated_at = datetime('now') WHERE id = 64;
UPDATE listings SET title = 'Straddie Views', updated_at = datetime('now') WHERE id = 65;
UPDATE listings SET title = 'Aquila Retreat', location = 'Buderim', updated_at = datetime('now') WHERE id = 68;
UPDATE listings SET title = 'Rainforest Cabins', location = 'Buderim', updated_at = datetime('now') WHERE id = 69;
UPDATE listings SET title = 'Drinks After Work', tagline = 'Social Friends', updated_at = datetime('now') WHERE id = 582;
UPDATE listings SET title = 'Your Matched', tagline = 'Speed Dating Dinners in Geelong', updated_at = datetime('now') WHERE id = 680;
UPDATE listings SET title = 'Amourlife', tagline = 'Speed Dating', updated_at = datetime('now') WHERE id = 805;

UPDATE businesses SET name = 'After Work Social Club', updated_at = datetime('now') WHERE id = 20;
UPDATE businesses SET name = 'Age of Miracles', updated_at = datetime('now') WHERE id = 22;
UPDATE businesses SET name = 'Barbs on the Walk', updated_at = datetime('now') WHERE id = 63;
UPDATE businesses SET name = 'Dr. Red Wine', updated_at = datetime('now') WHERE id = 64;
UPDATE businesses SET name = 'Straddie Views', updated_at = datetime('now') WHERE id = 65;
UPDATE businesses SET name = 'Aquila Retreat', updated_at = datetime('now') WHERE id = 68;
UPDATE businesses SET name = 'Rainforest Cabins', updated_at = datetime('now') WHERE id = 69;
UPDATE businesses SET name = 'Drinks After Work', updated_at = datetime('now') WHERE id = 582;
UPDATE businesses SET name = 'Your Matched', updated_at = datetime('now') WHERE id = 680;
UPDATE businesses SET name = 'Amourlife', updated_at = datetime('now') WHERE id = 806;
